CREATE TABLE pages (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

ALTER TABLE texts
ADD COLUMN page_id BIGINT;
ALTER TABLE texts
ADD CONSTRAINT fk_texts_pages
FOREIGN KEY (page_id)
REFERENCES pages(id) ON DELETE CASCADE;

ALTER TABLE images
ADD COLUMN page_id BIGINT;

ALTER TABLE images
ADD CONSTRAINT fk_images_pages
FOREIGN KEY (page_id)
REFERENCES pages(id) ON DELETE CASCADE;

ALTER TABLE texts ALTER COLUMN page_id SET NOT NULL;
ALTER TABLE images ALTER COLUMN page_id SET NOT NULL;